name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: yarn, build
        run: |
          yarn
          yarn build

      - name: run Lighthouse CI
        run: |
          yarn global add @lhci/cli@0.7.x
          lhci autorun

                 env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN  }}
      - run:
          name: lhci autorun
            yarn run lhci