name: dev
on: 
  push:  
    branches:
        - dev
      jobs:
        build:
        runs-on: ubuntu-latest
        uses: actions/checkout@v1
        - name: this is my name 
            run: echo 'I am dev'