name: dev
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run a turd factory
      run: |
       echo "I am on dev"
       echo "lets see if it works"
       echo "usess needs to be blocked out by a name"
